name: career_counsellor_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0

  # --- BACKEND CONNECTION ---
  http: ^1.1.0
  flutter_dotenv: ^5.1.0
  jwt_decoder: ^2.0.1
  flutter_secure_storage: ^10.0.0
  web: ^1.1.0

  # --- REAL-TIME CHAT ---
  web_socket_channel: ^2.4.0

  # --- VIDEO CALL (DYTE) ---
  permission_handler: ^11.3.0
  realtimekit_ui: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # --- ASSETS SECTION FOR .ENV ---
  assets:
    - .env